// web/lit/lit-javascript/src/lit-clock.js
import {LitElement, html} from 'lit';


class LitClock extends LitElement {
    static get properties() {
        return {
            _now: {state: true}
        }
    }

    constructor() {
        super();
        this._tick()
    }

    connectedCallback() {
        super.connectedCallback();
        this._scheduleTimeUpdate()
    }

    disconnectedCallback() {
        globalThis.clearTimeout(this._timeoutIdentifier)
        this._timeoutIdentifier = undefined
    }

    _scheduleTimeUpdate () {
        this._timeoutIdentifier = globalThis.setTimeout(() => {
            this._tick();
            this._scheduleTimeUpdate()
        }, 1000)
    }

    _tick() {
        this._now = new Date()
    }

    render() {
        return html`
            <div>
                <h1>Hello, world!</h1>
                <h2>It is ${this._now.toLocaleTimeString()}.</h2>
            </div>`
    }
}

customElements.define('lit-clock', LitClock);

// javascript/react-redux/src/components/clock.js
import React from "react";

export default class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  componentDidMount() {
    this.timerID = setInterval(
      () => this.tick(),
      1000
    );
  }

  componentWillUnmount() {
    clearInterval(this.timerID);
  }

  tick() {
    this.setState({
      date: new Date()
    });
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}
